nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
extraLabels: {}

server:
  image: docker.io/elabosak233/cdsctf:1.9.2
  replicas: 1

  persistence:
    size: 10Gi
    storageClass: "local-path"

  env:
    # Observability configuration
    CDSCTF_OBSERVE__SERVICE_NAME: "cdsctf"
    CDSCTF_OBSERVE__LOGGER__LEVEL: "info"
    CDSCTF_OBSERVE__EXPORTER__ENABLED: "false"

  service:
    type: ClusterIP # ClusterIP | NodePort | LoadBalancer | ExternalName
    nodePort: null
    loadBalancerIP: null
    loadBalancerSourceRanges: []
    externalTrafficPolicy: Cluster
    annotations:
      traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      traefik.ingress.kubernetes.io/service.sticky.cookie.name: "LB_Session"
      traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"

  serviceAccount:
    create: true
    clusterRoleBinding:
      create: true
      clusterRole: cluster-admin

db:
  enabled: true
  image: docker.io/library/postgres:18-alpine
  env:
    POSTGRES_USER: cdsctf
    POSTGRES_PASSWORD: cdsctf
    POSTGRES_DB: cdsctf

  persistence:
    size: 8Gi
    storageClass: "local-path"

queue:
  enabled: true
  image: docker.io/library/nats:2-alpine
  additionalArgs: []

  persistence:
    size: 1Gi
    storageClass: "local-path"

cache:
  enabled: true
  image: docker.io/valkey/valkey:9-alpine

  persistence:
    size: 1Gi
    storageClass: "local-path"

media:
  enabled: true
  image: docker.io/rustfs/rustfs:latest

  persistence:
    size: 128Gi
    storageClass: "local-path"
